# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db-service
spec:
  clusterIP: None
  selector:
    app: postgresql-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      
