# PostgreSQL StatefulSet Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-config
  labels:
    app: postgresql-db
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXMtdGVzdA==
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ==
