apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
spec:
  selector:
    app: marketplace-system
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer